owner: ticketplushq
repo: status

sites:
  - name: Ticketing (CHL1)
    icon: https://ticketing-assets.ticketplus.global/assets/logo-round-99223a5db65251ea5227316d3e30dbf03ac693920ffbca86b254f9508224754d.png
    url: $TICKETING_CHL1_ENDPOINT
  - name: Ticketing (ARG1)
    icon: https://ticketing-assets.ticketplus.global/assets/logo-round-99223a5db65251ea5227316d3e30dbf03ac693920ffbca86b254f9508224754d.png
    url: $TICKETING_ARG1_ENDPOINT
  - name: Ticketing (ARG2)
    icon: https://ticketing-assets.ticketplus.global/assets/logo-round-99223a5db65251ea5227316d3e30dbf03ac693920ffbca86b254f9508224754d.png
    url: $TICKETING_ARG1_ENDPOINT
  - name: Ticketing (PYG1)
    icon: https://ticketing-assets.ticketplus.global/assets/logo-round-99223a5db65251ea5227316d3e30dbf03ac693920ffbca86b254f9508224754d.png
    url: $TICKETING_PYG1_ENDPOINT
  - name: Cashless
    url: $CASHLESS_ENDPOINT
  - name: Netlink
    url: $NETLINK_ENDPOINT
  - name: Streame
    url: $STREAME_ENDPOINT
  - name: Vpass
    url: $VPASS_ENDPOINT
  - name: Reports
    url: $REPORTS_ENDPOINT
  - name: Enqueue
    url: $ENQUEUE_ENDPOINT

status-website:
  publish: true
  cname: status.ticketplus.global
  logoUrl: https://avatars.githubusercontent.com/u/30219716?s=200&v=4
  name: Ticketplus Global Status
  introTitle: "**Ticketplus Global Status** is the uptime monitor and status page, powered entirely by Upptime and Github."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
